"""add ai feedback table

Revision ID: 3118966b9573
Revises: 182805b6caea
Create Date: 2026-05-10 17:39:18.613752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3118966b9573'
down_revision = '182805b6caea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.String(length=20), nullable=False),
    sa.Column('generated_date', sa.String(length=20), nullable=False),
    sa.Column('data_hash', sa.String(length=100), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_feedback')
    # ### end Alembic commands ###
